#!/usr/bin/env python3
r"""
split-set.py — download a YouTube DJ set / compilation at highest audio quality
and split it into per-track files using a tracklist.

FEATURES
  * Keeps the source's NATIVE audio format by default (no transcode/quality loss).
    Opus stays opus, AAC stays m4a. Use --audio-format to force a conversion.
  * Tags each track: title, artist, album (= video title), album_artist (= channel),
    track number.
  * Album cover art from the video thumbnail, CENTER-CROPPED TO SQUARE (YouTube
    thumbs are 16:9 and look wrong in music players otherwise). --no-crop to keep 16:9.
  * Caches the downloaded source + thumbnail in ./.cache/ (auto-gitignored), keyed by
    video id + quality profile, so re-runs (e.g. tweaking the tracklist) DON'T
    re-download. --clean-cache removes this video's cache after a successful run.

Requires: yt-dlp and ffmpeg on PATH.
    macOS:  brew install yt-dlp ffmpeg
    termux: pkg install ffmpeg && pip install -U yt-dlp

TRACKLIST (default pattern):  mm:ss - Title - Artist   (h:mm:ss also works)
    0:00 - Intro - DJ Someone
    3:24 - Nightcall - Kavinsky
    1:02:15 - Closing - Someone Else
Each line's timestamp is the track START; next line's is its end (last runs to EOF).

USAGE
    ./split-set.py <URL> --tracklist tracks.txt
    ./split-set.py <URL> --from-description
    ./split-set.py <URL> --tracklist tracks.txt --dry-run
    ./split-set.py <URL> --tracklist tracks.txt --audio-format mp3
    ./split-set.py <URL> --tracklist tracks.txt --clean-cache
    ./split-set.py <URL> --tracklist tracks.txt \
        --regex '(?P<ts>[\d:]+)\s+(?P<artist>.+?)\s+-\s+(?P<title>.+)'
"""

import argparse
import glob
import json
import os
import re
import shutil
import subprocess
import sys

DEFAULT_REGEX = r'(?P<ts>\d{1,2}:\d{2}(?::\d{2})?)\s*[-\u2013\u2014]\s*(?P<title>.+?)\s*[-\u2013\u2014]\s*(?P<artist>.+)'
ART_EMBED_OK = {"m4a", "mp3", "aac"}
CACHE_DIR = ".cache"
COVER_SIZE = 1000  # px, square


def die(msg, code=1):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def check_deps():
    for tool in ("yt-dlp", "ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            die(f"'{tool}' not found on PATH. Install it and retry.")


def hms_to_seconds(ts):
    p = [int(x) for x in ts.split(":")]
    if len(p) == 2:
        return p[0] * 60 + p[1]
    if len(p) == 3:
        return p[0] * 3600 + p[1] * 60 + p[2]
    raise ValueError(f"bad timestamp: {ts}")


def sanitize(name):
    return re.sub(r'[/\\:*?"<>|]', "_", name).strip() or "track"


def ensure_cache():
    os.makedirs(CACHE_DIR, exist_ok=True)
    gi = os.path.join(CACHE_DIR, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w") as fh:
            fh.write("# auto-generated by split-set.py\n*\n")
    # also make sure the top-level .gitignore ignores the cache dir
    top = ".gitignore"
    line = f"{CACHE_DIR}/"
    existing = ""
    if os.path.exists(top):
        with open(top) as fh:
            existing = fh.read()
    if line not in existing:
        with open(top, "a") as fh:
            if existing and not existing.endswith("\n"):
                fh.write("\n")
            fh.write(f"{line}\n")


def fetch_info(url):
    print(">> fetching video info ...")
    res = subprocess.run(
        ["yt-dlp", "--no-playlist", "--dump-single-json", url],
        check=True, capture_output=True, text=True,
    )
    return json.loads(res.stdout)


def video_id(info, url):
    vid = (info or {}).get("id")
    if vid:
        return vid
    m = re.search(r'(?:v=|youtu\.be/|/shorts/)([A-Za-z0-9_-]{6,})', url)
    return m.group(1) if m else re.sub(r'\W+', '_', url)[-16:]


def probe_bestaudio_ext(url):
    try:
        res = subprocess.run(
            ["yt-dlp", "--no-playlist", "-f", "bestaudio/best",
             "--print", "%(ext)s", "--skip-download", url],
            check=True, capture_output=True, text=True,
        )
        ext = res.stdout.strip().splitlines()[-1].strip().lower()
        if ext in ("webm", "opus", "ogg"):
            return "opus"
        if ext in ("m4a", "mp4", "aac"):
            return "m4a"
        return ext or "m4a"
    except Exception:
        return "m4a"


def cached_source(vid, audio_format):
    """Return cached source path if present for this id+format, else None."""
    hits = glob.glob(os.path.join(CACHE_DIR, f"src_{vid}_{audio_format}.*"))
    return hits[0] if hits else None


def download_audio(url, vid, audio_format):
    existing = cached_source(vid, audio_format)
    if existing:
        print(f">> using cached source: {existing}")
        return existing
    out_tmpl = os.path.join(CACHE_DIR, f"src_{vid}_{audio_format}.%(ext)s")
    print(f">> downloading best-quality audio (format: {audio_format}) ...")
    subprocess.run(
        ["yt-dlp", "-f", "bestaudio/best", "-x", "--audio-format", audio_format,
         "--audio-quality", "0", "--no-playlist", "-o", out_tmpl, url],
        check=True,
    )
    return cached_source(vid, audio_format)


def get_cover(url, vid, crop):
    """Fetch thumbnail (cached), crop to square unless crop=False. Returns jpg path or None."""
    final = os.path.join(CACHE_DIR, f"cover_{vid}_{'sq' if crop else 'wide'}.jpg")
    if os.path.exists(final):
        print(f">> using cached cover: {final}")
        return final
    raw_tmpl = os.path.join(CACHE_DIR, f"thumbraw_{vid}.%(ext)s")
    try:
        subprocess.run(
            ["yt-dlp", "--no-playlist", "--skip-download", "--write-thumbnail",
             "--convert-thumbnails", "jpg", "-o", raw_tmpl, url],
            check=True, capture_output=True, text=True,
        )
    except subprocess.CalledProcessError:
        return None
    raws = glob.glob(os.path.join(CACHE_DIR, f"thumbraw_{vid}.jpg"))
    if not raws:
        return None
    raw = raws[0]
    if crop:
        # center-crop to square (min side), scale to COVER_SIZE
        vf = f"crop='min(iw,ih)':'min(iw,ih)',scale={COVER_SIZE}:{COVER_SIZE}"
        r = subprocess.run(
            ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
             "-i", raw, "-vf", vf, final],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            print(f"!! cover crop failed, using raw 16:9\n{r.stderr}", file=sys.stderr)
            shutil.copy2(raw, final)
    else:
        shutil.copy2(raw, final)
    return final


def parse_tracklist(text, pattern):
    rx = re.compile(pattern)
    out = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        m = rx.search(line)
        if not m:
            continue
        gd = m.groupdict()
        if not gd.get("ts"):
            continue
        try:
            start = hms_to_seconds(gd["ts"])
        except ValueError:
            continue
        out.append({"start": start,
                    "title": (gd.get("title") or "").strip(),
                    "artist": (gd.get("artist") or "").strip()})
    out.sort(key=lambda t: t["start"])
    return out


def get_duration(path):
    res = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nk=1:nw=1", path],
        check=True, capture_output=True, text=True,
    )
    return float(res.stdout.strip())


def split_tracks(src, tracks, outdir, fmt, album, album_artist, cover):
    os.makedirs(outdir, exist_ok=True)
    duration = get_duration(src)
    total = len(tracks)
    pad = len(str(total))
    embed_art = cover and fmt in ART_EMBED_OK
    for i, t in enumerate(tracks):
        start = t["start"]
        end = tracks[i + 1]["start"] if i + 1 < total else duration
        if end <= start:
            print(f"!! skipping '{t['title']}' (non-positive length)", file=sys.stderr)
            continue
        num = str(i + 1).zfill(pad)
        title = t["title"] or f"Track {num}"
        artist = t["artist"]
        base = f"{num} - {sanitize(title)}" + (f" - {sanitize(artist)}" if artist else "")
        out = os.path.join(outdir, base + f".{fmt}")
        meta = ["-metadata", f"title={title}", "-metadata", f"artist={artist}",
                "-metadata", f"album={album}", "-metadata", f"album_artist={album_artist}",
                "-metadata", f"track={i+1}/{total}"]
        if embed_art:
            cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                   "-ss", f"{start:.3f}", "-to", f"{end:.3f}", "-i", src, "-i", cover,
                   "-map", "0:a", "-map", "1:0", "-c:a", "copy", "-c:v", "mjpeg",
                   "-disposition:v", "attached_pic", *meta, out]
        else:
            cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                   "-ss", f"{start:.3f}", "-to", f"{end:.3f}", "-i", src,
                   "-map", "0:a", "-c", "copy", *meta, out]
        print(f"   [{num}/{total}] {title}" + (f" \u2014 {artist}" if artist else ""))
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            r2 = subprocess.run(
                ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                 "-ss", f"{start:.3f}", "-to", f"{end:.3f}", "-i", src,
                 "-map", "0:a", *meta, out],
                capture_output=True, text=True)
            if r2.returncode != 0:
                print(f"!! failed: {out}\n{r2.stderr}", file=sys.stderr)


def clean_video_cache(vid):
    removed = 0
    for f in glob.glob(os.path.join(CACHE_DIR, f"*{vid}*")):
        try:
            os.remove(f)
            removed += 1
        except OSError:
            pass
    print(f">> cleaned {removed} cached file(s) for {vid}")


def main():
    ap = argparse.ArgumentParser(description="Download & split a YouTube set into tagged tracks.")
    ap.add_argument("url")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--tracklist")
    src.add_argument("--from-description", action="store_true")
    ap.add_argument("--regex", default=DEFAULT_REGEX)
    ap.add_argument("--audio-format", default=None,
                    help="force format (m4a/mp3/opus/flac). Default: native.")
    ap.add_argument("-o", "--outdir", default=None)
    ap.add_argument("--album", default=None, help="override album (default: video title)")
    ap.add_argument("--no-cover", action="store_true")
    ap.add_argument("--no-crop", action="store_true", help="keep 16:9 thumbnail (don't square-crop)")
    ap.add_argument("--keep-full", action="store_true")
    ap.add_argument("--clean-cache", action="store_true", help="delete this video's cache after run")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not args.dry_run:
        check_deps()

    info = None
    if args.tracklist:
        if not os.path.isfile(args.tracklist):
            die(f"tracklist file not found: {args.tracklist}")
        with open(args.tracklist, encoding="utf-8") as fh:
            tl_text = fh.read()
    else:
        info = fetch_info(args.url)
        tl_text = info.get("description", "") or ""

    tracks = parse_tracklist(tl_text, args.regex)
    if not tracks:
        die("no tracks parsed. Check format or pass a custom --regex.\n"
            f"Pattern: {args.regex}")

    print(f">> parsed {len(tracks)} tracks:")
    for i, t in enumerate(tracks, 1):
        mm, ss = int(t["start"] // 60), int(t["start"] % 60)
        line = f"   {i:>2}. {mm:02d}:{ss:02d}  {t['title'] or '(untitled)'}"
        if t["artist"]:
            line += f" \u2014 {t['artist']}"
        print(line)

    if args.dry_run:
        return

    ensure_cache()
    if info is None:
        info = fetch_info(args.url)
    vid = video_id(info, args.url)
    album = args.album or info.get("title") or "Unknown Album"
    album_artist = info.get("uploader") or info.get("channel") or ""
    print(f">> album: {album}" + (f"  (album-artist: {album_artist})" if album_artist else ""))

    audio_format = args.audio_format or probe_bestaudio_ext(args.url)
    print(f">> output format: {audio_format}" + ("" if args.audio_format else " (native)"))

    source = download_audio(args.url, vid, audio_format)
    cover = None if args.no_cover else get_cover(args.url, vid, crop=not args.no_crop)
    if cover:
        print(">> cover art ready" + ("" if args.no_crop else " (square-cropped)"))

    outdir = args.outdir or (sanitize(album) + " - tracks")
    print(f">> splitting into: {outdir}")
    split_tracks(source, tracks, outdir, audio_format, album, album_artist, cover)

    if cover:
        shutil.copy2(cover, os.path.join(outdir, "cover.jpg"))
        print(">> wrote folder cover.jpg")
    if args.keep_full:
        shutil.copy2(source, os.path.join(outdir, "00 - FULL SET." + audio_format))
        print(">> kept full file")

    if args.clean_cache:
        clean_video_cache(vid)

    print(">> done.")


if __name__ == "__main__":
    main()
